### ISSUE TITLE
Coverage tests are run against lib

### ISSUE THREAD

**Issue by kesne** [zanuka/originator#15]
This generates inconsistent results because it is running against transpiled code, and also means the coveralls report can't include the original file source.

Isparta or something like https://github.com/ambitioninc/babel-istanbul might help.

**Comment by zanuka** [comment]
cool will fix.

**Comment by kesne** [comment]
Don't think this is fixed: https://coveralls.io/builds/3743597

**Comment by zanuka** [comment]
@kesne yeah it's on my list for the new version...
