### ISSUE TITLE
Lots of repetition in tasks

### ISSUE THREAD

**Issue by kesne** [zanuka/originator#16]
There's a lot of repetition in the tasks, especially around the test running. Ideally we could get that down a bit.

**Comment by zanuka** [comment]
Feel free to PR an alternate version. The idea for this starter module is that people will tweak the scripts to their own liking.

**Comment by kesne** [comment]
Yeah I'll spend some time tonight and try to think about it. May be best to keep things like this.

**Comment by zanuka** [comment]
I tried simplifying them before, but then found myself putting back in the clean tasks because I like to run the various scripts in random orders while testing sometimes. I'm totally open to suggestions and just want to make this as handy as possible for all. :surfer:

**Comment by zanuka** [comment]
would be cool to make a CLI for this so that many configurations could be created
